import dns from "node:dns";
import { config } from "dotenv";
import { MongoClient, ObjectId } from "mongodb";

config({ path: ".env.local" });

// Node's own resolver sometimes fails SRV lookups on Windows even when the OS
// resolver works fine (surfaces as "querySrv ECONNREFUSED"). Pointing it at a
// public resolver works around that for local dev; unrelated to prod (lib/mongodb.ts
// is untouched — Vercel's Linux runtime doesn't hit this).
dns.setServers(["8.8.8.8", "1.1.1.1"]);

interface SeedWord {
  word: string;
  partOfSpeech: string;
  definition: string;
  distractors: string[];
  exampleSentence: string;
  clozeSentence: string;
  difficulty: 1 | 2 | 3;
  ipa: string;
}

interface SeedVault {
  code: string;
  name: string;
  description: string;
  order: number;
  words: SeedWord[];
  /** Indexes into `words` that make up the 7-word heist, in escalating order. */
  heistIndexes: number[];
  caseFile: string;
}

const vaults: SeedVault[] = [
  {
    code: "V-07",
    name: "Corporate Boardroom",
    order: 1,
    description: "Ten floors up, the language is politer and the knives are sharper.",
    heistIndexes: [0, 1, 2, 3, 4, 7, 8],
    caseFile:
      "The boardroom lights stayed low after hours. Every stakeholder had gone home except one. She needed leverage, not luck. The merger papers promised synergy, but numbers rarely tell the truth. She'd built a contingency into the deal, a clause nobody read twice. Her acumen was the only asset the auditors couldn't seize. To streamline the exit, she signed as trustee, invoking her fiduciary duty one last time. By morning, the vault was empty. The board never saw it coming.",
    words: [
      {
        word: "leverage",
        partOfSpeech: "verb",
        definition: "to use something to maximum advantage",
        distractors: [
          "to postpone a decision until more data is available",
          "to formally reject a proposal in a meeting",
          "to delegate a task to a subordinate",
        ],
        exampleSentence: "The board decided to leverage its supplier relationships to negotiate better terms.",
        clozeSentence: "The board decided to ___ its supplier relationships to negotiate better terms.",
        difficulty: 1,
        ipa: "/ˈlɛvərɪdʒ/",
      },
      {
        word: "stakeholder",
        partOfSpeech: "noun",
        definition: "a person or group with an interest in a decision or project",
        distractors: [
          "a person who owns the majority of a company's shares",
          "an external auditor reviewing the accounts",
          "a temporary consultant hired for a single project",
        ],
        exampleSentence: "Every stakeholder was invited to weigh in before the merger was finalized.",
        clozeSentence: "Every ___ was invited to weigh in before the merger was finalized.",
        difficulty: 1,
        ipa: "/ˈsteɪkˌhoʊldər/",
      },
      {
        word: "synergy",
        partOfSpeech: "noun",
        definition: "the increased effectiveness produced by combined action",
        distractors: [
          "a formal agreement between two competing firms",
          "the total cost savings from layoffs",
          "a quarterly performance review process",
        ],
        exampleSentence: "The merger promised synergy between the two companies' distribution networks.",
        clozeSentence: "The merger promised ___ between the two companies' distribution networks.",
        difficulty: 1,
        ipa: "/ˈsɪnərdʒi/",
      },
      {
        word: "contingency",
        partOfSpeech: "noun",
        definition: "a provision for an unforeseen event or circumstance",
        distractors: [
          "a fixed percentage added to every invoice",
          "a mandatory training session for new hires",
          "a legal clause voiding a contract",
        ],
        exampleSentence: "The CFO insisted on a contingency plan before signing the lease.",
        clozeSentence: "The CFO insisted on a ___ plan before signing the lease.",
        difficulty: 2,
        ipa: "/kənˈtɪndʒənsi/",
      },
      {
        word: "streamline",
        partOfSpeech: "verb",
        definition: "to make a process more efficient by simplifying it",
        distractors: [
          "to expand a department by hiring more staff",
          "to outsource a function to a third party",
          "to postpone a launch indefinitely",
        ],
        exampleSentence: "New software helped streamline the approval process across departments.",
        clozeSentence: "New software helped ___ the approval process across departments.",
        difficulty: 2,
        ipa: "/ˈstriːmlaɪn/",
      },
      {
        word: "mandate",
        partOfSpeech: "noun",
        definition: "an official order or authorization to act in a particular way",
        distractors: [
          "a voluntary suggestion with no binding power",
          "a quarterly financial report",
          "an informal agreement between colleagues",
        ],
        exampleSentence: "Shareholders gave the new CEO a clear mandate to cut costs.",
        clozeSentence: "Shareholders gave the new CEO a clear ___ to cut costs.",
        difficulty: 2,
        ipa: "/ˈmændeɪt/",
      },
      {
        word: "attrition",
        partOfSpeech: "noun",
        definition: "the gradual reduction of staff through resignation or retirement",
        distractors: [
          "a sudden mass layoff announced without warning",
          "a bonus paid for long service",
          "a formal complaint filed by an employee",
        ],
        exampleSentence: "The company hoped to shrink headcount through attrition rather than layoffs.",
        clozeSentence: "The company hoped to shrink headcount through ___ rather than layoffs.",
        difficulty: 2,
        ipa: "/əˈtrɪʃən/",
      },
      {
        word: "fiduciary",
        partOfSpeech: "adjective",
        definition: "involving trust, especially the relationship between a trustee and a beneficiary",
        distractors: [
          "relating to the physical location of company headquarters",
          "describing a decision made without board approval",
          "referring to a temporary or provisional budget",
        ],
        exampleSentence: "Directors have a fiduciary duty to act in shareholders' best interests.",
        clozeSentence: "Directors have a ___ duty to act in shareholders' best interests.",
        difficulty: 3,
        ipa: "/fɪˈdjuːʃiəri/",
      },
      {
        word: "acumen",
        partOfSpeech: "noun",
        definition: "keen insight or shrewdness, especially in business matters",
        distractors: [
          "a formal certification required for executive roles",
          "the total value of a company's fixed assets",
          "a clause limiting an executive's liability",
        ],
        exampleSentence: "Her financial acumen helped the firm avoid a costly acquisition.",
        clozeSentence: "Her financial ___ helped the firm avoid a costly acquisition.",
        difficulty: 3,
        ipa: "/ˈækjəmən/",
      },
      {
        word: "exigent",
        partOfSpeech: "adjective",
        definition: "pressing, demanding immediate attention",
        distractors: [
          "related to a routine, scheduled review",
          "describing a cost that is fixed and predictable",
          "referring to a decision requiring unanimous consent",
        ],
        exampleSentence: "The exigent nature of the data breach forced an emergency board call.",
        clozeSentence: "The ___ nature of the data breach forced an emergency board call.",
        difficulty: 3,
        ipa: "/ˈɛksɪdʒənt/",
      },
    ],
  },
  {
    code: "V-12",
    name: "Tech Startup Slang",
    order: 2,
    description: "Ramen budgets, runway math, and a pitch deck that has to land perfectly.",
    heistIndexes: [0, 1, 2, 3, 4, 7, 8],
    caseFile:
      "Three founders, one server room, and six months of runway. They'd bootstrapped this far on ramen and stubbornness. When the metrics turned, they didn't panic, they pivot. Nobody had the bandwidth to explain it to the board twice. Churn was the real thief here, quietly draining users out the back door. Their only real moat was the code nobody else understood. The new investor wanted a bigger stake. Dilution, or dead. They signed at 2 a.m. and never looked back.",
    words: [
      {
        word: "runway",
        partOfSpeech: "noun",
        definition: "the amount of time before a startup runs out of cash",
        distractors: [
          "a company's total annual revenue",
          "the physical office space rented for a new team",
          "a scheduled product launch date",
        ],
        exampleSentence: "With only six months of runway left, the founders scrambled to close a funding round.",
        clozeSentence: "With only six months of ___ left, the founders scrambled to close a funding round.",
        difficulty: 1,
        ipa: "/ˈrʌnweɪ/",
      },
      {
        word: "pivot",
        partOfSpeech: "verb",
        definition: "to change a company's strategy or product direction significantly",
        distractors: [
          "to hire a large number of new employees quickly",
          "to relocate a company's headquarters overseas",
          "to file for bankruptcy protection",
        ],
        exampleSentence: "After the app flopped, the team decided to pivot toward enterprise clients.",
        clozeSentence: "After the app flopped, the team decided to ___ toward enterprise clients.",
        difficulty: 1,
        ipa: "/ˈpɪvət/",
      },
      {
        word: "bandwidth",
        partOfSpeech: "noun",
        definition: "a person's capacity to take on additional work or attention",
        distractors: [
          "the total number of engineers on a team",
          "a company's monthly cloud computing bill",
          "the speed at which code is deployed",
        ],
        exampleSentence: "I don't have the bandwidth to take on another project this sprint.",
        clozeSentence: "I don't have the ___ to take on another project this sprint.",
        difficulty: 1,
        ipa: "/ˈbændwɪdθ/",
      },
      {
        word: "bootstrap",
        partOfSpeech: "verb",
        definition: "to build a company without external investment",
        distractors: [
          "to raise a large seed round from venture capitalists",
          "to acquire a smaller competitor",
          "to release a product before it is fully tested",
        ],
        exampleSentence: "The founders chose to bootstrap the company for two years before taking any outside money.",
        clozeSentence: "The founders chose to ___ the company for two years before taking any outside money.",
        difficulty: 2,
        ipa: "/ˈbuːtstræp/",
      },
      {
        word: "churn",
        partOfSpeech: "noun",
        definition: "the rate at which customers stop using a product or service",
        distractors: [
          "the total revenue collected from new customers",
          "the number of bugs reported each month",
          "the frequency of product updates",
        ],
        exampleSentence: "High churn told them the onboarding flow was broken.",
        clozeSentence: "High ___ told them the onboarding flow was broken.",
        difficulty: 2,
        ipa: "/tʃɜːrn/",
      },
      {
        word: "scalable",
        partOfSpeech: "adjective",
        definition: "able to grow or be extended without a proportional increase in cost or effort",
        distractors: [
          "requiring manual approval for every transaction",
          "limited to a single geographic market",
          "dependent on a single key employee",
        ],
        exampleSentence: "Investors wanted proof the business model was scalable before writing a check.",
        clozeSentence: "Investors wanted proof the business model was ___ before writing a check.",
        difficulty: 2,
        ipa: "/ˈskeɪləbəl/",
      },
      {
        word: "traction",
        partOfSpeech: "noun",
        definition: "measurable evidence of growth or market interest",
        distractors: [
          "a formal partnership between two companies",
          "the total funding raised to date",
          "a company's employee retention rate",
        ],
        exampleSentence: "The product finally gained traction after a viral social post.",
        clozeSentence: "The product finally gained ___ after a viral social post.",
        difficulty: 2,
        ipa: "/ˈtrækʃən/",
      },
      {
        word: "moat",
        partOfSpeech: "noun",
        definition: "a durable competitive advantage that protects a business from rivals",
        distractors: [
          "a temporary discount used to win new customers",
          "a legal restriction on hiring competitors' employees",
          "the minimum viable version of a product",
        ],
        exampleSentence: "Their proprietary dataset gave them a moat competitors couldn't easily cross.",
        clozeSentence: "Their proprietary dataset gave them a ___ competitors couldn't easily cross.",
        difficulty: 3,
        ipa: "/moʊt/",
      },
      {
        word: "dilution",
        partOfSpeech: "noun",
        definition: "the reduction in existing shareholders' ownership percentage caused by issuing new shares",
        distractors: [
          "a decrease in a company's total valuation",
          "the process of simplifying a product's features",
          "a reduction in a founder's salary",
        ],
        exampleSentence: "Every funding round brought fresh capital, and fresh dilution.",
        clozeSentence: "Every funding round brought fresh capital, and fresh ___.",
        difficulty: 3,
        ipa: "/daɪˈluːʃən/",
      },
      {
        word: "inflection point",
        partOfSpeech: "noun",
        definition: "a moment of significant change in a company's growth trajectory",
        distractors: [
          "the exact date a company was founded",
          "a scheduled quarterly board meeting",
          "the point at which a founder steps down",
        ],
        exampleSentence: "The team could feel they'd hit an inflection point after the enterprise deal closed.",
        clozeSentence: "The team could feel they'd hit an ___ after the enterprise deal closed.",
        difficulty: 3,
        ipa: "/ɪnˈflɛkʃən pɔɪnt/",
      },
    ],
  },
  {
    code: "V-19",
    name: "Political Journalism",
    order: 3,
    description: "The embargo breaks at noon. Somebody in this building already broke it.",
    heistIndexes: [0, 1, 2, 3, 4, 7, 9],
    caseFile:
      "The leak came from inside her own constituency office. Someone had broken the embargo three hours early. The incumbent's team called it partisan sabotage, but the reporter knew better; this story was never political. It was personal. She'd promised a bipartisan piece, proof the two sides could agree on something. Instead she had a scandal and a mandate to print it. The senator threatened a filibuster on the next bill just to bury the news. She filed the story anyway, deadline be damned.",
    words: [
      {
        word: "constituency",
        partOfSpeech: "noun",
        definition: "a body of voters in a specified area who elect a representative",
        distractors: [
          "a formal debate between two political candidates",
          "a government agency responsible for elections",
          "a political party's official platform",
        ],
        exampleSentence: "The senator held a town hall to hear her constituency's concerns.",
        clozeSentence: "The senator held a town hall to hear her ___'s concerns.",
        difficulty: 1,
        ipa: "/kənˈstɪtjuənsi/",
      },
      {
        word: "partisan",
        partOfSpeech: "adjective",
        definition: "strongly supporting a particular party, cause, or person, often unfairly",
        distractors: [
          "relating to a nonprofit charitable organization",
          "describing a law passed unanimously",
          "referring to a retired official",
        ],
        exampleSentence: "The vote split along partisan lines, as expected.",
        clozeSentence: "The vote split along ___ lines, as expected.",
        difficulty: 1,
        ipa: "/ˈpɑːrtɪzən/",
      },
      {
        word: "mandate",
        partOfSpeech: "noun",
        definition: "authority granted by voters to a government to carry out a policy",
        distractors: [
          "a formal apology issued by a public official",
          "the minutes of a parliamentary session",
          "a temporary suspension of a law",
        ],
        exampleSentence: "The landslide victory gave the party a strong mandate to reform the tax code.",
        clozeSentence: "The landslide victory gave the party a strong ___ to reform the tax code.",
        difficulty: 1,
        ipa: "/ˈmændeɪt/",
      },
      {
        word: "embargo",
        partOfSpeech: "noun",
        definition: "an official ban on the release of information until a set time",
        distractors: [
          "a formal accusation of misconduct",
          "a scheduled press conference",
          "a government subsidy for local news outlets",
        ],
        exampleSentence: "Reporters agreed to the embargo until the report's official release at noon.",
        clozeSentence: "Reporters agreed to the ___ until the report's official release at noon.",
        difficulty: 2,
        ipa: "/ɛmˈbɑːrgoʊ/",
      },
      {
        word: "incumbent",
        partOfSpeech: "noun",
        definition: "the current holder of a political office",
        distractors: [
          "a candidate running for office for the first time",
          "an unelected government advisor",
          "a retired politician acting as a consultant",
        ],
        exampleSentence: "The incumbent faced a tough primary challenge from within her own party.",
        clozeSentence: "The ___ faced a tough primary challenge from within her own party.",
        difficulty: 2,
        ipa: "/ɪnˈkʌmbənt/",
      },
      {
        word: "redress",
        partOfSpeech: "verb",
        definition: "to remedy or set right an injustice or wrong",
        distractors: [
          "to formally introduce a new piece of legislation",
          "to postpone a scheduled vote",
          "to publicly criticize an opponent",
        ],
        exampleSentence: "Activists demanded the government redress decades of environmental neglect.",
        clozeSentence: "Activists demanded the government ___ decades of environmental neglect.",
        difficulty: 2,
        ipa: "/rɪˈdrɛs/",
      },
      {
        word: "gerrymander",
        partOfSpeech: "verb",
        definition: "to manipulate the boundaries of an electoral district for political advantage",
        distractors: [
          "to campaign door-to-door in a district",
          "to formally certify election results",
          "to fund a candidate's campaign anonymously",
        ],
        exampleSentence: "Critics accused the state legislature of trying to gerrymander the new map.",
        clozeSentence: "Critics accused the state legislature of trying to ___ the new map.",
        difficulty: 2,
        ipa: "/ˈdʒɛrimændər/",
      },
      {
        word: "bipartisan",
        partOfSpeech: "adjective",
        definition: "involving cooperation or agreement between two major political parties",
        distractors: [
          "describing a law that applies only to one state",
          "relating to a vote requiring a supermajority",
          "referring to an unelected advisory panel",
        ],
        exampleSentence: "The bill passed with rare bipartisan support in a divided Congress.",
        clozeSentence: "The bill passed with rare ___ support in a divided Congress.",
        difficulty: 3,
        ipa: "/baɪˈpɑːrtɪzən/",
      },
      {
        word: "disenfranchise",
        partOfSpeech: "verb",
        definition: "to deprive someone of the right to vote",
        distractors: [
          "to formally endorse a political candidate",
          "to remove a politician from office through impeachment",
          "to fund a public awareness campaign",
        ],
        exampleSentence: "The new ID law risked disenfranchising thousands of elderly voters.",
        clozeSentence: "The new ID law risked ___ thousands of elderly voters.",
        difficulty: 3,
        ipa: "/dɪsɪnˈfræntʃaɪz/",
      },
      {
        word: "filibuster",
        partOfSpeech: "noun",
        definition: "a tactic used to delay or block legislation by extending debate indefinitely",
        distractors: [
          "a formal vote to remove a sitting official",
          "a scheduled recess between legislative sessions",
          "an anonymous donation to a political campaign",
        ],
        exampleSentence: "The senator's filibuster stretched past midnight, delaying the final vote.",
        clozeSentence: "The senator's ___ stretched past midnight, delaying the final vote.",
        difficulty: 3,
        ipa: "/ˈfɪləbʌstər/",
      },
    ],
  },
  {
    code: "V-24",
    name: "High-Stakes Negotiation",
    order: 4,
    description: "Nobody blinks first. Nobody signs first either, not until the terms are right.",
    heistIndexes: [0, 1, 2, 3, 4, 7, 8],
    caseFile:
      "Midnight, and neither side would concede an inch. She'd walked in with real leverage: a second buyer waiting in the lobby. When talks hit an impasse, he tried brinkmanship, standing up like he might leave for good. She let him. He came back with a counteroffer twenty minutes later. She issued her own ultimatum next, take it before dawn or lose the exclusivity clause entirely. Neither wanted arbitration, the paperwork, the delay. So they signed on the hood of his car, in the parking garage light.",
    words: [
      {
        word: "concede",
        partOfSpeech: "verb",
        definition: "to admit or agree that a point in a negotiation goes to the other side",
        distractors: [
          "to formally end a business relationship",
          "to increase an offer without discussion",
          "to postpone a negotiation session",
        ],
        exampleSentence: "She refused to concede on price until shipping terms were settled.",
        clozeSentence: "She refused to ___ on price until shipping terms were settled.",
        difficulty: 1,
        ipa: "/kənˈsiːd/",
      },
      {
        word: "leverage",
        partOfSpeech: "noun",
        definition: "power or advantage that can be used to influence an outcome",
        distractors: [
          "a written summary of a negotiation's terms",
          "a fee paid to a mediator",
          "the final signed version of a contract",
        ],
        exampleSentence: "Knowing they had no other supplier gave her real leverage at the table.",
        clozeSentence: "Knowing they had no other supplier gave her real ___ at the table.",
        difficulty: 1,
        ipa: "/ˈlɛvərɪdʒ/",
      },
      {
        word: "impasse",
        partOfSpeech: "noun",
        definition: "a point in a negotiation where no progress can be made",
        distractors: [
          "a formal written agreement between two parties",
          "the opening offer in a negotiation",
          "a scheduled break during talks",
        ],
        exampleSentence: "Talks reached an impasse when neither side would move on price.",
        clozeSentence: "Talks reached an ___ when neither side would move on price.",
        difficulty: 1,
        ipa: "/ˈɪmpæs/",
      },
      {
        word: "counteroffer",
        partOfSpeech: "noun",
        definition: "a new offer made in response to one that was rejected",
        distractors: [
          "the final signed contract between two parties",
          "a legal penalty for breaking an agreement",
          "a formal apology issued after a dispute",
        ],
        exampleSentence: "Their counteroffer came in ten percent below the asking price.",
        clozeSentence: "Their ___ came in ten percent below the asking price.",
        difficulty: 2,
        ipa: "/ˈkaʊntərˌɒfər/",
      },
      {
        word: "ultimatum",
        partOfSpeech: "noun",
        definition: "a final demand, the rejection of which will result in consequences",
        distractors: [
          "a written summary of a meeting's outcomes",
          "a small concession offered early in talks",
          "a formal introduction between two negotiating parties",
        ],
        exampleSentence: "He issued an ultimatum: agree by Friday, or the deal was off.",
        clozeSentence: "He issued an ___: agree by Friday, or the deal was off.",
        difficulty: 2,
        ipa: "/ʌltɪˈmeɪtəm/",
      },
      {
        word: "mediator",
        partOfSpeech: "noun",
        definition: "a neutral party who helps two sides reach an agreement",
        distractors: [
          "a lawyer representing only one side of a dispute",
          "the person who signs a contract last",
          "an investor who funds a deal",
        ],
        exampleSentence: "A neutral mediator was brought in after talks broke down twice.",
        clozeSentence: "A neutral ___ was brought in after talks broke down twice.",
        difficulty: 2,
        ipa: "/ˈmiːdieɪtər/",
      },
      {
        word: "concession",
        partOfSpeech: "noun",
        definition: "something given up or granted in order to reach an agreement",
        distractors: [
          "a formal signature required to close a deal",
          "a penalty for late payment",
          "a summary document sent after negotiations",
        ],
        exampleSentence: "Every concession was traded carefully, never given for free.",
        clozeSentence: "Every ___ was traded carefully, never given for free.",
        difficulty: 2,
        ipa: "/kənˈsɛʃən/",
      },
      {
        word: "brinkmanship",
        partOfSpeech: "noun",
        definition: "the practice of pushing a dangerous situation to the limit to gain advantage",
        distractors: [
          "a formal strategy document prepared before talks",
          "the process of verifying a contract's legal terms",
          "a negotiation style based on early compromise",
        ],
        exampleSentence: "His brinkmanship nearly collapsed the deal twice before it closed.",
        clozeSentence: "His ___ nearly collapsed the deal twice before it closed.",
        difficulty: 3,
        ipa: "/ˈbrɪŋkmənʃɪp/",
      },
      {
        word: "arbitration",
        partOfSpeech: "noun",
        definition: "a process where a dispute is settled by an impartial third party outside of court",
        distractors: [
          "an informal conversation to resolve a minor disagreement",
          "the initial stage of a business merger",
          "a public vote on a company policy",
        ],
        exampleSentence: "The contract required binding arbitration instead of a courtroom trial.",
        clozeSentence: "The contract required binding ___ instead of a courtroom trial.",
        difficulty: 3,
        ipa: "/ɑːrbɪˈtreɪʃən/",
      },
      {
        word: "leverage point",
        partOfSpeech: "noun",
        definition: "a specific factor that gives one party significant negotiating power",
        distractors: [
          "the final clause added to a signed contract",
          "a scheduled deadline for submitting an offer",
          "a formal apology issued mid-negotiation",
        ],
        exampleSentence: "Their exclusive patent was the leverage point that ended the standoff.",
        clozeSentence: "Their exclusive patent was the ___ that ended the standoff.",
        difficulty: 3,
        ipa: "/ˈlɛvərɪdʒ pɔɪnt/",
      },
    ],
  },
  {
    code: "V-31",
    name: "Back-Alley Idioms",
    order: 5,
    description: "The dictionary won't help you here. This is how people actually talk.",
    heistIndexes: [0, 1, 2, 3, 4, 7, 8],
    caseFile:
      "The firm had been in the red for months, and someone had started cutting corners to hide it. Payments moved under the table, quiet as smoke. She should have read the room the moment the accountant stopped making eye contact. He'd burned every bridge trying to cover it, blaming juniors, deleting logs. Then she found it: one email, the smoking gun. Every company had skeletons in the closet. This one just forgot to lock the door.",
    words: [
      {
        word: "cut corners",
        partOfSpeech: "verb phrase",
        definition: "to do something in the easiest or cheapest way, often sacrificing quality",
        distractors: [
          "to finish a task well ahead of schedule",
          "to negotiate a lower price aggressively",
          "to divide profits evenly among partners",
        ],
        exampleSentence: "The contractor decided to cut corners on the wiring, and it nearly cost them the building.",
        clozeSentence: "The contractor decided to ___ on the wiring, and it nearly cost them the building.",
        difficulty: 1,
        ipa: "/kʌt ˈkɔːrnərz/",
      },
      {
        word: "read the room",
        partOfSpeech: "verb phrase",
        definition: "to accurately judge the mood or attitude of a group of people",
        distractors: [
          "to give a formal presentation to an audience",
          "to review a document before signing it",
          "to memorize a script before a meeting",
        ],
        exampleSentence: "He failed to read the room and kept joking after the bad news landed.",
        clozeSentence: "He failed to ___ and kept joking after the bad news landed.",
        difficulty: 1,
        ipa: "/riːd ðə ruːm/",
      },
      {
        word: "burn bridges",
        partOfSpeech: "verb phrase",
        definition: "to destroy relationships or opportunities in a way that cannot be undone",
        distractors: [
          "to invest heavily in a risky new venture",
          "to resolve a conflict amicably",
          "to retire from a position gracefully",
        ],
        exampleSentence: "She quit without notice, choosing to burn bridges she'd spent years building.",
        clozeSentence: "She quit without notice, choosing to ___ she'd spent years building.",
        difficulty: 1,
        ipa: "/bɜːrn ˈbrɪdʒɪz/",
      },
      {
        word: "in the red",
        partOfSpeech: "adjective phrase",
        definition: "operating at a financial loss",
        distractors: [
          "under investigation by regulators",
          "ahead of schedule on a project",
          "in violation of a contract",
        ],
        exampleSentence: "The store had been in the red for three straight quarters.",
        clozeSentence: "The store had been ___ for three straight quarters.",
        difficulty: 2,
        ipa: "/ɪn ðə rɛd/",
      },
      {
        word: "under the table",
        partOfSpeech: "adverb phrase",
        definition: "done secretly, especially involving illegal or undisclosed payment",
        distractors: [
          "done publicly and with full documentation",
          "postponed until further review",
          "agreed upon by all parties in writing",
        ],
        exampleSentence: "Investigators suspected the payments were made under the table.",
        clozeSentence: "Investigators suspected the payments were made ___.",
        difficulty: 2,
        ipa: "/ˈʌndər ðə ˈteɪbəl/",
      },
      {
        word: "throw under the bus",
        partOfSpeech: "verb phrase",
        definition: "to blame or betray someone, often to protect oneself",
        distractors: [
          "to publicly defend a colleague under pressure",
          "to promote someone ahead of schedule",
          "to quietly resolve a dispute between coworkers",
        ],
        exampleSentence: "When the numbers came up short, he threw his assistant under the bus.",
        clozeSentence: "When the numbers came up short, he ___ his assistant.",
        difficulty: 2,
        ipa: "/θroʊ ˈʌndər ðə bʌs/",
      },
      {
        word: "keep at arm's length",
        partOfSpeech: "verb phrase",
        definition: "to avoid becoming too close or involved with someone",
        distractors: [
          "to promote someone to a senior position",
          "to invite someone into a close partnership",
          "to formally introduce someone to a client",
        ],
        exampleSentence: "After the betrayal, she kept her old business partner at arm's length.",
        clozeSentence: "After the betrayal, she ___ her old business partner.",
        difficulty: 2,
        ipa: "/kiːp æt ɑːrmz lɛŋθ/",
      },
      {
        word: "smoking gun",
        partOfSpeech: "noun phrase",
        definition: "definitive evidence of a crime or wrongdoing",
        distractors: [
          "a minor clue with no real significance",
          "a formal legal document filed in court",
          "a witness who refuses to testify",
        ],
        exampleSentence: "The email was the smoking gun investigators had been searching for.",
        clozeSentence: "The email was the ___ investigators had been searching for.",
        difficulty: 3,
        ipa: "/ˈsmoʊkɪŋ gʌn/",
      },
      {
        word: "skeletons in the closet",
        partOfSpeech: "noun phrase",
        definition: "hidden secrets or past misdeeds a person or organization wants to conceal",
        distractors: [
          "a list of upcoming projects kept confidential",
          "a company's official code of conduct",
          "unused office space in a building",
        ],
        exampleSentence: "Every board member seemed to have a few skeletons in the closet.",
        clozeSentence: "Every board member seemed to have a few ___.",
        difficulty: 3,
        ipa: "/ˈskɛlətənz ɪn ðə ˈklɒzɪt/",
      },
      {
        word: "cover your tracks",
        partOfSpeech: "verb phrase",
        definition: "to hide evidence of one's actions to avoid detection",
        distractors: [
          "to double-check a document before submission",
          "to formally apologize for a mistake",
          "to publicly announce a decision",
        ],
        exampleSentence: "He deleted the files carefully, trying to cover his tracks.",
        clozeSentence: "He deleted the files carefully, trying to ___.",
        difficulty: 3,
        ipa: "/ˈkʌvər jɔːr træks/",
      },
    ],
  },
];

// "Training" tier: beginner vocabulary extracted from docs/toefl-primary-vocab.md
// (docs/Step1 TOEFL Book1.pdf). Kept fully separate from the B2/C1 core vaults —
// see docs/design.md. These vaults are always unlocked (app/api/vaults/route.ts)
// and never participate in the core vault-unlock chain.
const trainingVaults: SeedVault[] = [
  {
    code: "T-01",
    name: "My Family",
    order: 1,
    description: "The basics every rookie starts with: who's who around the table.",
    heistIndexes: [0, 1, 2, 9, 14, 17, 18],
    caseFile:
      "First day on the job, and the trainer wanted names. Grandparents first, she said, always start with grandparents. He listed his: grandfather, grandmother, both retired, both nosy. His parents were divorced, which made the next question harder. Whose side do you work? He picked his nephew instead, safer ground. By the end of the file he'd mapped the whole family: grandchildren, in-laws, everyone. The trainer nodded. Good. Now do it in under a minute.",
    words: [
      {
        word: "grandparents",
        partOfSpeech: "noun",
        definition: "the parents of one's father or mother",
        distractors: [
          "the children of one's brother or sister",
          "the brothers and sisters of one's parents",
          "the parents of one's husband or wife",
        ],
        exampleSentence: "Every summer, the children stay with their grandparents in the countryside.",
        clozeSentence: "Every summer, the children stay with their ___ in the countryside.",
        difficulty: 1,
        ipa: "/ˈɡrænˌpɛərənts/",
      },
      {
        word: "grandfather",
        partOfSpeech: "noun",
        definition: "the father of one's father or mother",
        distractors: [
          "the brother of one's mother or father",
          "the husband of one's aunt",
          "the father of one's husband or wife",
        ],
        exampleSentence: "My grandfather tells the best stories about his childhood.",
        clozeSentence: "My ___ tells the best stories about his childhood.",
        difficulty: 1,
        ipa: "/ˈɡrænfɑːðər/",
      },
      {
        word: "grandmother",
        partOfSpeech: "noun",
        definition: "the mother of one's father or mother",
        distractors: [
          "the sister of one's mother or father",
          "the wife of one's uncle",
          "the mother of one's husband or wife",
        ],
        exampleSentence: "My grandmother bakes cookies for us every weekend.",
        clozeSentence: "My ___ bakes cookies for us every weekend.",
        difficulty: 1,
        ipa: "/ˈɡrænmʌðər/",
      },
      {
        word: "aunt",
        partOfSpeech: "noun",
        definition: "the sister of one's mother or father, or the wife of one's uncle",
        distractors: [
          "the daughter of one's brother or sister",
          "the mother of one's cousin's spouse",
          "the wife of one's grandfather",
        ],
        exampleSentence: "My aunt lives in the city with her husband.",
        clozeSentence: "My ___ lives in the city with her husband.",
        difficulty: 1,
        ipa: "/ænt/",
      },
      {
        word: "uncle",
        partOfSpeech: "noun",
        definition: "the brother of one's mother or father, or the husband of one's aunt",
        distractors: [
          "the son of one's brother or sister",
          "the father of one's cousin's spouse",
          "the husband of one's grandmother",
        ],
        exampleSentence: "My uncle takes me fishing every summer.",
        clozeSentence: "My ___ takes me fishing every summer.",
        difficulty: 1,
        ipa: "/ˈʌŋkəl/",
      },
      {
        word: "mother",
        partOfSpeech: "noun",
        definition: "a female parent",
        distractors: ["a female grandparent", "a female cousin", "a female in-law"],
        exampleSentence: "My mother works as a nurse at the hospital.",
        clozeSentence: "My ___ works as a nurse at the hospital.",
        difficulty: 1,
        ipa: "/ˈmʌðər/",
      },
      {
        word: "father",
        partOfSpeech: "noun",
        definition: "a male parent",
        distractors: ["a male grandparent", "a male cousin", "a male in-law"],
        exampleSentence: "My father drives me to school every morning.",
        clozeSentence: "My ___ drives me to school every morning.",
        difficulty: 1,
        ipa: "/ˈfɑːðər/",
      },
      {
        word: "sister",
        partOfSpeech: "noun",
        definition: "a female sibling",
        distractors: ["a female cousin", "a female niece", "a female grandchild"],
        exampleSentence: "My sister and I share a room.",
        clozeSentence: "My ___ and I share a room.",
        difficulty: 1,
        ipa: "/ˈsɪstər/",
      },
      {
        word: "brother",
        partOfSpeech: "noun",
        definition: "a male sibling",
        distractors: ["a male cousin", "a male nephew", "a male grandchild"],
        exampleSentence: "My brother taught me how to ride a bike.",
        clozeSentence: "My ___ taught me how to ride a bike.",
        difficulty: 1,
        ipa: "/ˈbrʌðər/",
      },
      {
        word: "divorced",
        partOfSpeech: "adjective",
        definition: "no longer married, having legally ended a marriage",
        distractors: [
          "engaged to be married",
          "living together but not married",
          "widowed after a spouse's death",
        ],
        exampleSentence: "My parents are divorced, but they still get along well.",
        clozeSentence: "My parents are ___, but they still get along well.",
        difficulty: 2,
        ipa: "/dɪˈvɔːrst/",
      },
      {
        word: "wife",
        partOfSpeech: "noun",
        definition: "a married woman, in relation to her spouse",
        distractors: [
          "an unmarried woman engaged to be married",
          "a woman who has never been married",
          "a female business partner",
        ],
        exampleSentence: "He introduced his wife to all of his coworkers.",
        clozeSentence: "He introduced his ___ to all of his coworkers.",
        difficulty: 1,
        ipa: "/waɪf/",
      },
      {
        word: "husband",
        partOfSpeech: "noun",
        definition: "a married man, in relation to his spouse",
        distractors: [
          "an unmarried man engaged to be married",
          "a man who has never been married",
          "a male business partner",
        ],
        exampleSentence: "Her husband cooks dinner every Friday night.",
        clozeSentence: "Her ___ cooks dinner every Friday night.",
        difficulty: 1,
        ipa: "/ˈhʌzbənd/",
      },
      {
        word: "daughter",
        partOfSpeech: "noun",
        definition: "a female child, in relation to her parents",
        distractors: [
          "a female grandchild, in relation to her grandparents",
          "a female sibling",
          "a female cousin",
        ],
        exampleSentence: "Their daughter just started her first year of college.",
        clozeSentence: "Their ___ just started her first year of college.",
        difficulty: 1,
        ipa: "/ˈdɔːtər/",
      },
      {
        word: "son",
        partOfSpeech: "noun",
        definition: "a male child, in relation to his parents",
        distractors: [
          "a male grandchild, in relation to his grandparents",
          "a male sibling",
          "a male cousin",
        ],
        exampleSentence: "Their son wants to be a doctor when he grows up.",
        clozeSentence: "Their ___ wants to be a doctor when he grows up.",
        difficulty: 1,
        ipa: "/sʌn/",
      },
      {
        word: "nephew",
        partOfSpeech: "noun",
        definition: "the son of one's brother or sister",
        distractors: [
          "the son of one's aunt or uncle",
          "the son of one's cousin",
          "a young male family friend",
        ],
        exampleSentence: "I took my nephew to the zoo last weekend.",
        clozeSentence: "I took my ___ to the zoo last weekend.",
        difficulty: 2,
        ipa: "/ˈnɛfjuː/",
      },
      {
        word: "niece",
        partOfSpeech: "noun",
        definition: "the daughter of one's brother or sister",
        distractors: [
          "the daughter of one's aunt or uncle",
          "the daughter of one's cousin",
          "a young female family friend",
        ],
        exampleSentence: "My niece just turned five years old.",
        clozeSentence: "My ___ just turned five years old.",
        difficulty: 2,
        ipa: "/niːs/",
      },
      {
        word: "cousin",
        partOfSpeech: "noun",
        definition: "the child of one's aunt or uncle",
        distractors: [
          "the child of one's sibling",
          "the sibling of one's parent",
          "the parent of one's sibling's spouse",
        ],
        exampleSentence: "My cousin and I grew up in the same neighborhood.",
        clozeSentence: "My ___ and I grew up in the same neighborhood.",
        difficulty: 1,
        ipa: "/ˈkʌzən/",
      },
      {
        word: "grandchildren",
        partOfSpeech: "noun",
        definition: "the children of one's son or daughter",
        distractors: [
          "the children of one's brother or sister",
          "the children of one's cousin",
          "the younger siblings of one's children",
        ],
        exampleSentence: "She loves spoiling her grandchildren with candy and toys.",
        clozeSentence: "She loves spoiling her ___ with candy and toys.",
        difficulty: 3,
        ipa: "/ˈɡrænˌtʃɪldrən/",
      },
      {
        word: "in-laws",
        partOfSpeech: "noun",
        definition: "the relatives of one's husband or wife",
        distractors: [
          "close family friends treated like relatives",
          "the parents of one's cousin",
          "distant relatives one has never met",
        ],
        exampleSentence: "We're having dinner with my in-laws this weekend.",
        clozeSentence: "We're having dinner with my ___ this weekend.",
        difficulty: 3,
        ipa: "/ˈɪn lɔːz/",
      },
      {
        word: "married",
        partOfSpeech: "adjective",
        definition: "having a husband or wife; joined in marriage",
        distractors: [
          "engaged but not yet wed",
          "living alone and unattached",
          "recently divorced",
        ],
        exampleSentence: "They have been married for over twenty years.",
        clozeSentence: "They have been ___ for over twenty years.",
        difficulty: 1,
        ipa: "/ˈmærid/",
      },
    ],
  },
  {
    code: "T-02",
    name: "Appearances",
    order: 2,
    description: "Learn to describe a face well enough that someone else could pick it out.",
    heistIndexes: [0, 1, 2, 3, 4, 17, 18],
    caseFile:
      "The photo was blurry, but the description wasn't. Long hair, the witness said, maybe short hair under a hat, hard to tell. A mustache, definitely a mustache, and a face full of freckles like she'd counted them herself. Every wrinkle mattered too, she insisted, especially the ones by his eyes. He smiled once, she remembered, just once, and there was a dimple on the left side. Even the pimple on his chin made it into her statement. Small details. That's what training was for.",
    words: [
      {
        word: "long hair",
        partOfSpeech: "noun phrase",
        definition: "hair that extends well past the shoulders or is notably lengthy",
        distractors: [
          "hair that is shaved very close to the scalp",
          "hair styled into tight curls",
          "hair dyed a bright, unnatural color",
        ],
        exampleSentence: "She's had long hair since she was a little girl.",
        clozeSentence: "She's had ___ since she was a little girl.",
        difficulty: 1,
        ipa: "/lɔːŋ hɛər/",
      },
      {
        word: "short hair",
        partOfSpeech: "noun phrase",
        definition: "hair that is cut close to the head, above the shoulders",
        distractors: [
          "hair that reaches down to the waist",
          "hair tied up in a high bun",
          "hair with a single long braid",
        ],
        exampleSentence: "He got a short hair cut before starting his new job.",
        clozeSentence: "He got a ___ cut before starting his new job.",
        difficulty: 1,
        ipa: "/ʃɔːrt hɛər/",
      },
      {
        word: "mustache",
        partOfSpeech: "noun",
        definition: "hair that grows on a man's upper lip",
        distractors: [
          "hair that grows along the jawline",
          "hair that grows on the chin only",
          "thick eyebrows that meet in the middle",
        ],
        exampleSentence: "My grandfather has had the same mustache for forty years.",
        clozeSentence: "My grandfather has had the same ___ for forty years.",
        difficulty: 1,
        ipa: "/ˈmʌstæʃ/",
      },
      {
        word: "freckle",
        partOfSpeech: "noun",
        definition: "a small light brown spot on the skin, often caused by the sun",
        distractors: [
          "a small red bump caused by an allergy",
          "a scar left from an old injury",
          "a birthmark present since birth",
        ],
        exampleSentence: "Her nose is covered in freckles from the summer sun.",
        clozeSentence: "Her nose is covered in ___s from the summer sun.",
        difficulty: 2,
        ipa: "/ˈfrɛkəl/",
      },
      {
        word: "wrinkle",
        partOfSpeech: "noun",
        definition: "a small fold or line in the skin, often from aging",
        distractors: [
          "a dimple that appears when smiling",
          "a scar left after healing",
          "a patch of dry, flaky skin",
        ],
        exampleSentence: "He has a few wrinkles around his eyes when he smiles.",
        clozeSentence: "He has a few ___s around his eyes when he smiles.",
        difficulty: 2,
        ipa: "/ˈrɪŋkəl/",
      },
      {
        word: "bald",
        partOfSpeech: "adjective",
        definition: "having little or no hair on the head",
        distractors: [
          "having very long, thick hair",
          "having hair dyed gray",
          "having hair tied back tightly",
        ],
        exampleSentence: "My uncle started going bald in his early thirties.",
        clozeSentence: "My uncle started going ___ in his early thirties.",
        difficulty: 1,
        ipa: "/bɔːld/",
      },
      {
        word: "beard",
        partOfSpeech: "noun",
        definition: "hair that grows on the chin and jaw of a man's face",
        distractors: [
          "hair that grows on the scalp only",
          "hair styled into a ponytail",
          "eyebrows that are unusually thick",
        ],
        exampleSentence: "He grew a beard over the winter break.",
        clozeSentence: "He grew a ___ over the winter break.",
        difficulty: 1,
        ipa: "/bɪərd/",
      },
      {
        word: "curly hair",
        partOfSpeech: "noun phrase",
        definition: "hair that grows or is styled into tight curves or spirals",
        distractors: [
          "hair that hangs perfectly flat and smooth",
          "hair shaved close to the scalp",
          "hair styled with a single side part",
        ],
        exampleSentence: "Everyone in her family has curly hair except her.",
        clozeSentence: "Everyone in her family has ___ except her.",
        difficulty: 1,
        ipa: "/ˈkɜːrli hɛər/",
      },
      {
        word: "ponytail",
        partOfSpeech: "noun",
        definition: "hair gathered and tied at the back of the head so it hangs down",
        distractors: [
          "hair braided into several small sections",
          "hair cut extremely short all over",
          "hair pinned up into a bun",
        ],
        exampleSentence: "She wears her hair in a ponytail when she plays sports.",
        clozeSentence: "She wears her hair in a ___ when she plays sports.",
        difficulty: 1,
        ipa: "/ˈpoʊniˌteɪl/",
      },
      {
        word: "glasses",
        partOfSpeech: "noun",
        definition: "a pair of lenses in a frame worn to help someone see better",
        distractors: [
          "small lenses worn directly on the eyes",
          "dark lenses worn to block sunlight",
          "a magnifying tool held in the hand",
        ],
        exampleSentence: "He can't read the board without his glasses.",
        clozeSentence: "He can't read the board without his ___.",
        difficulty: 1,
        ipa: "/ˈɡlæsɪz/",
      },
      {
        word: "tall",
        partOfSpeech: "adjective",
        definition: "having a greater than average height",
        distractors: [
          "having a smaller than average build",
          "having a heavier than average build",
          "having an unusually thin frame",
        ],
        exampleSentence: "My brother is the tallest person in our family.",
        clozeSentence: "My brother is the ___est person in our family.",
        difficulty: 1,
        ipa: "/tɔːl/",
      },
      {
        word: "short",
        partOfSpeech: "adjective",
        definition: "having a less than average height",
        distractors: [
          "having a greater than average height",
          "having a heavier than average build",
          "having an unusually pale complexion",
        ],
        exampleSentence: "She's quite short, so she always sits in the front row.",
        clozeSentence: "She's quite ___, so she always sits in the front row.",
        difficulty: 1,
        ipa: "/ʃɔːrt/",
      },
      {
        word: "thin",
        partOfSpeech: "adjective",
        definition: "having little body fat; slim",
        distractors: [
          "having a heavier, rounder build",
          "having a tall, broad frame",
          "having noticeably pale skin",
        ],
        exampleSentence: "He's always been thin, no matter how much he eats.",
        clozeSentence: "He's always been ___, no matter how much he eats.",
        difficulty: 1,
        ipa: "/θɪn/",
      },
      {
        word: "chubby",
        partOfSpeech: "adjective",
        definition: "somewhat plump or rounded, especially in a soft, endearing way",
        distractors: [
          "extremely tall and thin",
          "muscular and athletic",
          "unusually pale and thin",
        ],
        exampleSentence: "The baby has the chubbiest little cheeks.",
        clozeSentence: "The baby has the ___est little cheeks.",
        difficulty: 2,
        ipa: "/ˈtʃʌbi/",
      },
      {
        word: "scratch",
        partOfSpeech: "noun",
        definition: "a thin mark or cut on the skin or a surface",
        distractors: [
          "a deep bruise under the skin",
          "a small burn mark",
          "a permanent scar from surgery",
        ],
        exampleSentence: "He got a scratch on his arm from the cat.",
        clozeSentence: "He got a ___ on his arm from the cat.",
        difficulty: 2,
        ipa: "/skrætʃ/",
      },
      {
        word: "straight hair",
        partOfSpeech: "noun phrase",
        definition: "hair that hangs flat and smooth without curls or waves",
        distractors: [
          "hair that curls tightly at the ends",
          "hair that is shaved on the sides",
          "hair styled into small braids",
        ],
        exampleSentence: "Her straight hair reaches all the way to her waist.",
        clozeSentence: "Her ___ reaches all the way to her waist.",
        difficulty: 1,
        ipa: "/streɪt hɛər/",
      },
      {
        word: "bangs",
        partOfSpeech: "noun",
        definition: "hair cut short and worn hanging over the forehead",
        distractors: [
          "hair shaved close on the sides only",
          "hair tied into two small buns",
          "hair dyed a lighter color at the tips",
        ],
        exampleSentence: "She cut bangs to change up her look.",
        clozeSentence: "She cut ___ to change up her look.",
        difficulty: 2,
        ipa: "/bæŋz/",
      },
      {
        word: "dimple",
        partOfSpeech: "noun",
        definition: "a small natural indentation in the skin, especially in the cheek when smiling",
        distractors: [
          "a small scar from a childhood injury",
          "a freckle near the mouth",
          "a wrinkle that appears with age",
        ],
        exampleSentence: "He has a dimple in his left cheek when he grins.",
        clozeSentence: "He has a ___ in his left cheek when he grins.",
        difficulty: 3,
        ipa: "/ˈdɪmpəl/",
      },
      {
        word: "pimple",
        partOfSpeech: "noun",
        definition: "a small, raised, inflamed spot on the skin",
        distractors: [
          "a small brown spot caused by the sun",
          "a natural fold in the skin",
          "a permanent mark left by a scar",
        ],
        exampleSentence: "She had a pimple on her chin before the school photo.",
        clozeSentence: "She had a ___ on her chin before the school photo.",
        difficulty: 3,
        ipa: "/ˈpɪmpəl/",
      },
      {
        word: "height",
        partOfSpeech: "noun",
        definition: "how tall a person or thing is",
        distractors: [
          "how much a person or thing weighs",
          "how old a person is",
          "how wide a person or thing is",
        ],
        exampleSentence: "The nurse measured his height and weight at the check-up.",
        clozeSentence: "The nurse measured his ___ and weight at the check-up.",
        difficulty: 1,
        ipa: "/haɪt/",
      },
    ],
  },
  {
    code: "T-03",
    name: "At the Library",
    order: 3,
    description: "Quiet rooms, paper trails, and a due date nobody can talk their way out of.",
    heistIndexes: [0, 1, 2, 4, 5, 13, 19],
    caseFile:
      "The librarian remembered everything, that was the problem. He'd asked for a library card under a fake name, forgotten the book report was due, dropped an overdue notice at the check-out desk without thinking twice. She matched the handwriting to three other cards before closing. He'd have gotten away with it if he'd just returned the book on time. Instead she circled the due date in red, filed the report, and waited by the shelves. Some crimes leave fingerprints. His left a paper trail.",
    words: [
      {
        word: "librarian",
        partOfSpeech: "noun",
        definition: "a person who works in and manages a library",
        distractors: [
          "a person who writes books for a living",
          "a student who studies at the library",
          "a person who sells books in a store",
        ],
        exampleSentence: "The librarian helped me find a book on ancient Egypt.",
        clozeSentence: "The ___ helped me find a book on ancient Egypt.",
        difficulty: 1,
        ipa: "/laɪˈbrɛəriən/",
      },
      {
        word: "library",
        partOfSpeech: "noun",
        definition: "a building or room containing books available to borrow or read",
        distractors: [
          "a store where books are bought and sold",
          "a room used only for quiet studying",
          "a building where old documents are kept locked away",
        ],
        exampleSentence: "We spent the afternoon studying at the library.",
        clozeSentence: "We spent the afternoon studying at the ___.",
        difficulty: 1,
        ipa: "/ˈlaɪbrɛri/",
      },
      {
        word: "book",
        partOfSpeech: "noun",
        definition: "a set of printed pages bound together, usually with a cover",
        distractors: [
          "a single loose sheet of printed paper",
          "a short article printed in a newspaper",
          "a digital file with no printed form",
        ],
        exampleSentence: "She read her favorite book three times last year.",
        clozeSentence: "She read her favorite ___ three times last year.",
        difficulty: 1,
        ipa: "/bʊk/",
      },
      {
        word: "magazine",
        partOfSpeech: "noun",
        definition: "a thin periodical publication with articles and pictures, published regularly",
        distractors: [
          "a daily printed sheet of local news",
          "a bound book of short stories",
          "a pamphlet given out for free at events",
        ],
        exampleSentence: "He reads a car magazine every month.",
        clozeSentence: "He reads a car ___ every month.",
        difficulty: 1,
        ipa: "/ˌmæɡəˈziːn/",
      },
      {
        word: "library card",
        partOfSpeech: "noun phrase",
        definition: "a card that allows a person to borrow books from a library",
        distractors: [
          "a card used only to enter the building",
          "a receipt given after paying a late fee",
          "a card that lists a reader's favorite books",
        ],
        exampleSentence: "You need a library card to check out books.",
        clozeSentence: "You need a ___ to check out books.",
        difficulty: 2,
        ipa: "/ˈlaɪbrɛri kɑːrd/",
      },
      {
        word: "book report",
        partOfSpeech: "noun phrase",
        definition: "a written summary and opinion of a book a student has read",
        distractors: [
          "a list of every book in the library",
          "a note explaining why a book is overdue",
          "a form used to request a new book",
        ],
        exampleSentence: "My teacher assigned a book report due next Friday.",
        clozeSentence: "My teacher assigned a ___ due next Friday.",
        difficulty: 2,
        ipa: "/bʊk rɪˈpɔːrt/",
      },
      {
        word: "read a book",
        partOfSpeech: "verb phrase",
        definition: "to look at and understand the words in a book",
        distractors: [
          "to write a summary of a book",
          "to return a book to the shelf",
          "to search the shelves for a book",
        ],
        exampleSentence: "I like to read a book before I go to sleep.",
        clozeSentence: "I like to ___ before I go to sleep.",
        difficulty: 1,
        ipa: "/riːd ə bʊk/",
      },
      {
        word: "overdue",
        partOfSpeech: "adjective",
        definition: "not returned by the date it was due",
        distractors: [
          "recently published and newly available",
          "reserved for another reader",
          "missing a page or cover",
        ],
        exampleSentence: "My library book is two days overdue.",
        clozeSentence: "My library book is two days ___.",
        difficulty: 2,
        ipa: "/ˌoʊvərˈduː/",
      },
      {
        word: "fill out",
        partOfSpeech: "verb phrase",
        definition: "to complete a form by writing in the required information",
        distractors: [
          "to return a form after reading it",
          "to throw away an old, unused form",
          "to copy a form for someone else",
        ],
        exampleSentence: "Please fill out this form to get a library card.",
        clozeSentence: "Please ___ this form to get a library card.",
        difficulty: 2,
        ipa: "/fɪl aʊt/",
      },
      {
        word: "check out",
        partOfSpeech: "verb phrase",
        definition: "to borrow an item from a library using your card",
        distractors: [
          "to return an item to the library shelf",
          "to search the library catalog for a title",
          "to pay a fee owed to the library",
        ],
        exampleSentence: "I checked out three books for my summer reading list.",
        clozeSentence: "I ___ed three books for my summer reading list.",
        difficulty: 1,
        ipa: "/tʃɛk aʊt/",
      },
      {
        word: "return a book",
        partOfSpeech: "verb phrase",
        definition: "to bring a borrowed book back to the library",
        distractors: [
          "to borrow a book from the library",
          "to buy a book from a store",
          "to donate a book to the library",
        ],
        exampleSentence: "Don't forget to return a book before the due date.",
        clozeSentence: "Don't forget to ___ before the due date.",
        difficulty: 1,
        ipa: "/rɪˈtɜːrn ə bʊk/",
      },
      {
        word: "look for a book",
        partOfSpeech: "verb phrase",
        definition: "to search for a specific book",
        distractors: [
          "to write a review of a book",
          "to organize books by author",
          "to pay the fee for a book",
        ],
        exampleSentence: "She spent an hour looking for a book on the shelves.",
        clozeSentence: "She spent an hour ___ing for a book on the shelves.",
        difficulty: 1,
        ipa: "/lʊk fɔːr ə bʊk/",
      },
      {
        word: "newspaper",
        partOfSpeech: "noun",
        definition: "a printed publication containing news, published daily or weekly",
        distractors: [
          "a monthly publication focused on a single topic",
          "a bound collection of short stories",
          "a printed schedule of library events",
        ],
        exampleSentence: "My grandfather reads the newspaper every morning with his coffee.",
        clozeSentence: "My grandfather reads the ___ every morning with his coffee.",
        difficulty: 1,
        ipa: "/ˈnuːzˌpeɪpər/",
      },
      {
        word: "check-out desk",
        partOfSpeech: "noun phrase",
        definition: "the counter where library items are borrowed or returned",
        distractors: [
          "a desk reserved for quiet studying",
          "the librarian's private office",
          "a table where new books are displayed",
        ],
        exampleSentence: "Bring your books to the check-out desk when you're ready.",
        clozeSentence: "Bring your books to the ___ when you're ready.",
        difficulty: 3,
        ipa: "/ˈtʃɛk aʊt dɛsk/",
      },
      {
        word: "pay",
        partOfSpeech: "verb",
        definition: "to give money for something owed or purchased",
        distractors: [
          "to borrow money for later use",
          "to refuse to give money owed",
          "to receive money as a gift",
        ],
        exampleSentence: "You have to pay a small fee for a lost library card.",
        clozeSentence: "You have to ___ a small fee for a lost library card.",
        difficulty: 1,
        ipa: "/peɪ/",
      },
      {
        word: "quiet",
        partOfSpeech: "adjective",
        definition: "making very little or no noise",
        distractors: [
          "extremely loud and disruptive",
          "brightly lit and busy",
          "crowded with many people talking",
        ],
        exampleSentence: "The library is always quiet in the early morning.",
        clozeSentence: "The library is always ___ in the early morning.",
        difficulty: 1,
        ipa: "/ˈkwaɪət/",
      },
      {
        word: "noise",
        partOfSpeech: "noun",
        definition: "a sound, especially one that is loud or unwanted",
        distractors: [
          "a complete absence of any sound",
          "a written warning about being too loud",
          "a quiet whisper between two people",
        ],
        exampleSentence: "Please don't make any noise in the reading room.",
        clozeSentence: "Please don't make any ___ in the reading room.",
        difficulty: 1,
        ipa: "/nɔɪz/",
      },
      {
        word: "late fee",
        partOfSpeech: "noun phrase",
        definition: "money charged for returning something after its due date",
        distractors: [
          "money paid to reserve a popular book",
          "money given as a deposit for a library card",
          "money refunded for a damaged book",
        ],
        exampleSentence: "I paid a late fee because I forgot to return the book.",
        clozeSentence: "I paid a ___ because I forgot to return the book.",
        difficulty: 2,
        ipa: "/leɪt fiː/",
      },
      {
        word: "available",
        partOfSpeech: "adjective",
        definition: "able to be used or obtained; not currently in use by someone else",
        distractors: [
          "checked out and currently unavailable",
          "permanently removed from the collection",
          "reserved for library staff only",
        ],
        exampleSentence: "That book isn't available right now; someone else has it.",
        clozeSentence: "That book isn't ___ right now; someone else has it.",
        difficulty: 2,
        ipa: "/əˈveɪləbəl/",
      },
      {
        word: "due date",
        partOfSpeech: "noun phrase",
        definition: "the date by which a borrowed item must be returned",
        distractors: [
          "the date a book was first published",
          "the date a library card expires",
          "the date new books arrive at the library",
        ],
        exampleSentence: "The due date for this book is next Monday.",
        clozeSentence: "The ___ for this book is next Monday.",
        difficulty: 3,
        ipa: "/duː deɪt/",
      },
    ],
  },
  {
    code: "T-04",
    name: "At School",
    order: 4,
    description: "Hallways, homeroom, and a report card that tells on everyone.",
    heistIndexes: [0, 1, 2, 5, 15, 13, 17],
    caseFile:
      "They'd tracked him from elementary school to middle school to high school, three different files, same handwriting in the margins. The principal remembered him best, said he skipped every semester review without fail. His class schedule was a work of fiction, more free periods than classes. Once, during an assembly, they found him hiding in the auditorium long after everyone left. Nobody could prove anything. He always had a hallway pass, always somewhere else on paper. The file stayed open for years.",
    words: [
      {
        word: "elementary school",
        partOfSpeech: "noun phrase",
        definition: "a school for the first years of a child's education, typically ages five to eleven",
        distractors: [
          "a school attended only by teenagers",
          "a school for advanced university study",
          "a school that teaches only one subject",
        ],
        exampleSentence: "My little sister just started elementary school this year.",
        clozeSentence: "My little sister just started ___ this year.",
        difficulty: 1,
        ipa: "/ˌɛləˈmɛntri skuːl/",
      },
      {
        word: "middle school",
        partOfSpeech: "noun phrase",
        definition: "a school between elementary and high school, typically for ages eleven to fourteen",
        distractors: [
          "the final years of university study",
          "a school only for young children",
          "an evening school for adults",
        ],
        exampleSentence: "He made a lot of new friends in middle school.",
        clozeSentence: "He made a lot of new friends in ___.",
        difficulty: 1,
        ipa: "/ˈmɪdəl skuːl/",
      },
      {
        word: "high school",
        partOfSpeech: "noun phrase",
        definition: "a school after middle school, typically for ages fourteen to eighteen",
        distractors: [
          "a school for children under five",
          "a school that only teaches sports",
          "a university graduate program",
        ],
        exampleSentence: "She's a junior in high school this year.",
        clozeSentence: "She's a junior in ___ this year.",
        difficulty: 1,
        ipa: "/haɪ skuːl/",
      },
      {
        word: "teacher",
        partOfSpeech: "noun",
        definition: "a person who instructs students in a school",
        distractors: [
          "a person who manages the whole school",
          "a person who cleans the classrooms",
          "a student who helps other students",
        ],
        exampleSentence: "My science teacher makes every lesson fun.",
        clozeSentence: "My science ___ makes every lesson fun.",
        difficulty: 1,
        ipa: "/ˈtiːtʃər/",
      },
      {
        word: "student",
        partOfSpeech: "noun",
        definition: "a person who is studying at a school",
        distractors: [
          "a person who teaches at a school",
          "a person who manages a school",
          "a parent who volunteers at school",
        ],
        exampleSentence: "Every student needs a notebook for class.",
        clozeSentence: "Every ___ needs a notebook for class.",
        difficulty: 1,
        ipa: "/ˈstuːdənt/",
      },
      {
        word: "principal",
        partOfSpeech: "noun",
        definition: "the person in charge of running a school",
        distractors: [
          "a teacher who leads a single classroom",
          "a student elected to represent their class",
          "a parent who volunteers at the school",
        ],
        exampleSentence: "The principal welcomed all the new students on the first day.",
        clozeSentence: "The ___ welcomed all the new students on the first day.",
        difficulty: 2,
        ipa: "/ˈprɪnsəpəl/",
      },
      {
        word: "classroom",
        partOfSpeech: "noun",
        definition: "a room in a school where lessons take place",
        distractors: [
          "a room where school lunches are served",
          "a room used only for school meetings",
          "an outdoor area used for sports",
        ],
        exampleSentence: "Our classroom has twenty-five desks.",
        clozeSentence: "Our ___ has twenty-five desks.",
        difficulty: 1,
        ipa: "/ˈklæsˌruːm/",
      },
      {
        word: "gym",
        partOfSpeech: "noun",
        definition: "a room or building equipped for physical exercise or sports",
        distractors: [
          "a room where students eat lunch",
          "a room used for science experiments",
          "a room where books are stored",
        ],
        exampleSentence: "We play basketball in the gym on Fridays.",
        clozeSentence: "We play basketball in the ___ on Fridays.",
        difficulty: 1,
        ipa: "/dʒɪm/",
      },
      {
        word: "cafeteria",
        partOfSpeech: "noun",
        definition: "a room in a school where meals are served",
        distractors: [
          "a room used for physical education",
          "a room where students store their belongings",
          "a hallway that connects classrooms",
        ],
        exampleSentence: "The cafeteria serves pizza every Wednesday.",
        clozeSentence: "The ___ serves pizza every Wednesday.",
        difficulty: 1,
        ipa: "/ˌkæfəˈtɪriə/",
      },
      {
        word: "subject",
        partOfSpeech: "noun",
        definition: "an area of study, such as math or history",
        distractors: [
          "a grade given at the end of a semester",
          "a room where a class is held",
          "a schedule of daily classes",
        ],
        exampleSentence: "Math is my favorite subject in school.",
        clozeSentence: "Math is my favorite ___ in school.",
        difficulty: 1,
        ipa: "/ˈsʌbdʒɪkt/",
      },
      {
        word: "locker",
        partOfSpeech: "noun",
        definition: "a small storage compartment, often with a lock, used to store belongings",
        distractors: [
          "a small room used for private study",
          "a schoolbag carried on the back",
          "a shelf in the school library",
        ],
        exampleSentence: "I keep my books in my locker between classes.",
        clozeSentence: "I keep my books in my ___ between classes.",
        difficulty: 1,
        ipa: "/ˈlɒkər/",
      },
      {
        word: "restroom",
        partOfSpeech: "noun",
        definition: "a room with toilets, available for public or student use",
        distractors: [
          "a room where students rest between classes",
          "a room used to store cleaning supplies",
          "a small office for school nurses",
        ],
        exampleSentence: "May I be excused to use the restroom?",
        clozeSentence: "May I be excused to use the ___?",
        difficulty: 1,
        ipa: "/ˈrɛstˌruːm/",
      },
      {
        word: "school bus",
        partOfSpeech: "noun phrase",
        definition: "a bus used to transport students to and from school",
        distractors: [
          "a van used only for school field trips",
          "a private car service for teachers",
          "a train used for long school trips",
        ],
        exampleSentence: "I take the school bus every morning at 7 a.m.",
        clozeSentence: "I take the ___ every morning at 7 a.m.",
        difficulty: 1,
        ipa: "/skuːl bʌs/",
      },
      {
        word: "auditorium",
        partOfSpeech: "noun",
        definition: "a large room where audiences gather for performances or assemblies",
        distractors: [
          "a small room used for private tutoring",
          "a room where sports equipment is kept",
          "an outdoor field used for assemblies",
        ],
        exampleSentence: "The whole school gathered in the auditorium for the concert.",
        clozeSentence: "The whole school gathered in the ___ for the concert.",
        difficulty: 3,
        ipa: "/ˌɔːdɪˈtɔːriəm/",
      },
      {
        word: "hallway",
        partOfSpeech: "noun",
        definition: "a long passage in a building that connects rooms",
        distractors: [
          "a small room used for quiet study",
          "an outdoor path between school buildings",
          "a room where lockers are stored",
        ],
        exampleSentence: "Students aren't allowed to run in the hallway.",
        clozeSentence: "Students aren't allowed to run in the ___.",
        difficulty: 1,
        ipa: "/ˈhɔːlweɪ/",
      },
      {
        word: "class schedule",
        partOfSpeech: "noun phrase",
        definition: "a list showing what classes happen at what times",
        distractors: [
          "a list of a student's final grades",
          "a map showing the layout of the school",
          "a calendar of school holidays",
        ],
        exampleSentence: "Check your class schedule to see when math starts.",
        clozeSentence: "Check your ___ to see when math starts.",
        difficulty: 2,
        ipa: "/klæs ˈskɛdʒuːl/",
      },
      {
        word: "report card",
        partOfSpeech: "noun phrase",
        definition: "an official document showing a student's grades",
        distractors: [
          "a card used to check out library books",
          "a note excusing a student's absence",
          "a card listing a student's class schedule",
        ],
        exampleSentence: "My parents were proud when they saw my report card.",
        clozeSentence: "My parents were proud when they saw my ___.",
        difficulty: 2,
        ipa: "/rɪˈpɔːrt kɑːrd/",
      },
      {
        word: "semester",
        partOfSpeech: "noun",
        definition: "one of two main periods that make up a school year",
        distractors: [
          "a single day of school lessons",
          "a short weekly quiz",
          "an extra class held after school",
        ],
        exampleSentence: "Final exams happen at the end of each semester.",
        clozeSentence: "Final exams happen at the end of each ___.",
        difficulty: 3,
        ipa: "/səˈmɛstər/",
      },
      {
        word: "recess",
        partOfSpeech: "noun",
        definition: "a break during the school day for play or rest",
        distractors: [
          "the final class period of the day",
          "a mandatory after-school study session",
          "a meeting between teachers and parents",
        ],
        exampleSentence: "The kids played tag together at recess.",
        clozeSentence: "The kids played tag together at ___.",
        difficulty: 1,
        ipa: "/ˈriːsɛs/",
      },
      {
        word: "science lab",
        partOfSpeech: "noun phrase",
        definition: "a room equipped for conducting science experiments",
        distractors: [
          "a room used only for art projects",
          "a room where school records are stored",
          "a quiet room reserved for reading",
        ],
        exampleSentence: "We mixed chemicals safely in the science lab.",
        clozeSentence: "We mixed chemicals safely in the ___.",
        difficulty: 2,
        ipa: "/ˈsaɪəns læb/",
      },
    ],
  },
];

async function seed() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error("Missing MONGODB_URI. Set it in .env.local before seeding.");
    process.exit(1);
  }

  const client = new MongoClient(uri);
  await client.connect();
  const db = client.db(process.env.MONGODB_DB || "word_heist");

  await db.collection("vaults").deleteMany({});
  await db.collection("words").deleteMany({});

  async function seedGroup(group: SeedVault[], tier: "core" | "training") {
    for (const vault of group) {
      const vaultId = new ObjectId();
      const wordIds = vault.words.map(() => new ObjectId());

      const wordDocs = vault.words.map((w, i) => ({
        _id: wordIds[i],
        word: w.word,
        partOfSpeech: w.partOfSpeech,
        definition: w.definition,
        distractors: w.distractors,
        exampleSentence: w.exampleSentence,
        clozeSentence: w.clozeSentence,
        vaultId,
        difficulty: w.difficulty,
        ipa: w.ipa,
      }));

      await db.collection("words").insertMany(wordDocs);

      await db.collection("vaults").insertOne({
        _id: vaultId,
        code: vault.code,
        name: vault.name,
        description: vault.description,
        order: vault.order,
        wordCount: vault.words.length,
        heistWordIds: vault.heistIndexes.map((i) => wordIds[i]),
        caseFile: vault.caseFile,
        tier,
      });

      console.log(`Seeded ${vault.code} - ${vault.name} (${vault.words.length} words) [${tier}]`);
    }
  }

  await seedGroup(vaults, "core");
  await seedGroup(trainingVaults, "training");

  await db.collection("players").createIndex({ playerId: 1 }, { unique: true });
  await db.collection("runs").createIndex({ playerId: 1 });
  await db.collection("words").createIndex({ vaultId: 1 });

  const allVaults = [...vaults, ...trainingVaults];
  console.log(
    `Done. Seeded ${allVaults.length} vaults (${vaults.length} core + ${trainingVaults.length} training) / ${allVaults.reduce((n, v) => n + v.words.length, 0)} words.`
  );
  await client.close();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
